language: node_js
node_js: stable

install:
  - npm install

script:
  - hexo clean
  - hexo generate

after_script:
  - cd ./public
  - git init 
  - git config user.name "tiandi0228"
  - git config user.email "tiandi0228@live.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/tiandi0228/tiandi0228.github.io.git